services:
  - type: web
    name: aboud-bot
    env: docker
    envVars:
      - key: GITHUB_CLONE_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WHISPER_BOT_TOKEN
        sync: false
      - key: QRAN_BOT_TOKEN
        sync: false
      - key: WHATSAPP_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GIST_ID
        sync: false
      - key: The_OwnDev_Can_Run_Only
        value: "ABOUD_87E7CAA14B42BCF73A3D70EB"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BAILEYS_PORT
        value: "3001"
      - key: PYTHON_WEBHOOK
        value: "http://localhost:5000/wa_webhook"
