services:
  - type: web
    name: aboud-bot
    env: image
    image:
      url: docker.io/mido101/sourceaboud:latest
    envVars:
      - key: API_ID
      - key: API_HASH
      - key: BOT_TOKEN
      - key: WHISPER_BOT_TOKEN
      - key: QRAN_BOT_TOKEN
      - key: WHATSAPP_BOT_TOKEN
      - key: GROQ_API_KEY
      - key: DATABASE_URL
      - key: GITHUB_TOKEN
      - key: GIST_ID
      - key: The_OwnDev_Can_Run_Only
        value: "ABOUD_87E7CAA14B42BCF73A3D70EB"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BAILEYS_PORT
        value: "3001"
      - key: PYTHON_WEBHOOK
        value: "http://localhost:5000/wa_webhook"
